module.exports = [
	'affenpinscher',
	'afghan hound',
	'airedale terrier',
	'akita',
	'alaskan husky',
	'alaskan klee kai',
	'alaskan malamute',
	'alpine mastiff',
	'alpine spaniel',
	'american akita',
	'american bulldog',
	'american cocker spaniel',
	'american english coonhound',
	'american eskimo dog',
	'american foxhound',
	'american hairless terrier',
	'american pit bull terrier',
	'american staffordshire terrier',
	'american water spaniel',
	'anatolian shepherd dog',
	'australian cattle dog',
	'australian kelpie',
	'australian shepherd',
	'australian silky terrier',
	'australian terrier',
	'austrian black and tan hound',
	'austrian pinscher',
	'barbet',
	'basenji',
	'grand basset griffon vendeen',
	'petit basset griffon vendeen',
	'basset hound',
	'bavarian mountain hound',
	'beagle',
	'bearded collie',
	'beauceron',
	'bedlington terrier',
	'belgian malinois',
	'belgian tervuren',
	'berger picard',
	'bernese mountain dog',
	'bichon frise',
	'black and tan coonhound',
	'black and tan virginia foxhound',
	'black norwegian elkhound',
	'black russian terrier',
	'bloodhound',
	'blue paul terrier',
	'blue picardy spaniel',
	'bluetick coonhound',
	'boerboel',
	'bohemian shepherd',
	'border collie',
	'border terrier',
	'borzoi',
	'bosnian coarse-haired hound',
	'boston terrier',
	'bouvier des ardennes',
	'bouvier des flandres',
	'boxer',
	'boykin spaniel',
	'briard',
	'brittany',
	'bull terrier',
	'miniature bull terrier',
	'bulldog',
	'bullenbeisser',
	'bullmastiff',
	'cairn terrier',
	'canaan dog',
	'canadian eskimo dog',
	'cane corso',
	'cantabrian water dog',
	'carolina dog',
	'carpathian shepherd dog',
	'catahoula leopard dog',
	'catalan sheepdog',
	'caucasian shepherd dog',
	'cavalier king charles spaniel',
	'central asian shepherd dog',
	'cesky terrier',
	'chesapeake bay retriever',
	'chihuahua',
	'chilean fox terrier',
	'chinese chongqing dog',
	'chinese crested dog',
	'chinese imperial dog',
	'chinook',
	'chow chow',
	'clumber spaniel',
	'rough collie',
	'smooth collie',
	'coton de tulear',
	'cretan hound',
	'croatian sheepdog',
	'cumberland sheepdog',
	'curly-coated retriever',
	'czechoslovakian wolfdog',
	'dachshund',
	'dalmatian',
	'dandie dinmont terrier',
	'danish-swedish farmdog',
	'doberman pinscher',
	'dogue de bordeaux',
	'dutch shepherd',
	'dutch smoushond',
	'east siberian laika',
	'east european shepherd',
	'english cocker spaniel',
	'english foxhound',
	'english mastiff',
	'english setter',
	'english shepherd',
	'english springer spaniel',
	'black and tan english toy terrier',
	'english water spaniel',
	'english white terrier',
	'entlebucher mountain dog',
	'estonian hound',
	'field spaniel',
	'finnish hound',
	'finnish lapphund',
	'finnish spitz',
	'flat-coated retriever',
	'smooth fox terrier',
	'wire fox terrier',
	'french bulldog',
	'french spaniel',
	'galician cattle dog',
	'german longhaired pointer',
	'german pinscher',
	'german roughhaired pointer',
	'german shepherd dog',
	'german shorthaired pointer',
	'german spaniel',
	'german spitz',
	'german wirehaired pointer',
	'giant schnauzer',
	'glen of imaal terrier',
	'golden retriever',
	'gordon setter',
	'gran mastin de borinquen',
	'grand griffon vendeen',
	'great dane',
	'great pyrenees',
	'greater swiss mountain dog',
	'greyhound',
	'harrier',
	'havanese',
	'ibizan hound',
	'icelandic sheepdog',
	'indian pariah dog',
	'indian spitz',
	'irish red and white setter',
	'irish setter',
	'irish terrier',
	'irish water spaniel',
	'irish wolfhound',
	'italian greyhound',
	'jack russell terrier',
	'japanese chin',
	'japanese spitz',
	'japanese terrier',
	'karelian bear dog',
	'keeshond',
	'kerry blue terrier',
	'king charles spaniel',
	'komondor',
	'kuvasz',
	'labrador husky',
	'labrador retriever',
	'lagotto romagnolo',
	'lakeland terrier',
	'lancashire heeler',
	'leonberger',
	'lhasa apso',
	'lowchen',
	'maltese',
	'manchester terrier',
	'mexican hairless dog',
	'miniature fox terrier',
	'miniature pinscher',
	'miniature schnauzer',
	'neapolitan mastiff',
	'newfoundland',
	'norfolk spaniel',
	'norfolk terrier',
	'norwegian buhund',
	'norwegian elkhound',
	'norwegian lundehund',
	'norwich terrier',
	'nova scotia duck tolling retriever',
	'old english sheepdog',
	'otterhound',
	'paisley terrier',
	'papillon',
	'parson russell terrier',
	'patterdale terrier',
	'pekingese',
	'peruvian hairless dog',
	'pharaoh hound',
	'picardy spaniel',
	'plummer terrier',
	'plott hound',
	'pointer',
	'polish lowland sheepdog',
	'pomeranian',
	'poodle',
	'portuguese water dog',
	'pug',
	'puli',
	'pyrenean mastiff',
	'pyrenean shepherd',
	'redbone coonhound',
	'rhodesian ridgeback',
	'rottweiler',
	'russian spaniel',
	'russell terrier',
	'saluki',
	'samoyed',
	'schipperke',
	'standard schnauzer',
	'scotch collie',
	'scottish deerhound',
	'scottish terrier',
	'sealyham terrier',
	'shar pei',
	'shetland sheepdog',
	'shiba inu',
	'shih tzu',
	'shiloh shepherd',
	'siberian husky',
	'skye terrier',
	'soft-coated wheaten terrier',
	'spanish mastiff',
	'spinone italiano',
	'st bernard',
	'st john\'s water dog',
	'staffordshire bull terrier',
	'sussex spaniel',
	'swedish lapphund',
	'swedish vallhund',
	'teddy roosevelt terrier',
	'tenterfield terrier',
	'tibetan mastiff',
	'tibetan spaniel',
	'tibetan terrier',
	'toy fox terrier',
	'toy manchester terrier',
	'toy trawler spaniel',
	'transylvanian hound',
	'treeing cur',
	'treeing tennessee brindle',
	'treeing walker coonhound',
	'tweed water spaniel',
	'vizsla',
	'volpino italiano',
	'weimaraner',
	'cardigan welsh corgi',
	'pembroke welsh corgi',
	'welsh sheepdog',
	'welsh springer spaniel',
	'welsh terrier',
	'west highland white terrier',
	'whippet',
	'wirehaired pointing griffon',
	'wirehaired vizsla',
	'yorkshire terrier',
  'labradoodle',
  'goldendoodle',
  'cavoodle',
  'schnoodle',
  'chorkie',
  'chiweenie',
  'puggle',
  'groodle',
  'cavachon',
  'pekapoo',
];
