module.exports = [
  'australian silky terrier',
  'brussels griffon',
  'bichon frise',
  'border terrier',
  'bouvier des flandres',
  'basenji',
  'chinese crested',
  'cairn terrier',
  'golden retriever',
  'havanese',
  'irish water spaniel',
  'kerry blue terrier',
  'labradoodle',
  'maltese terrier',
  'maltese',
  'pekingese',
  'portugese water dog',
  'poodle',
  'shih tzu',
  'soft coated wheaten terrier',
  'scottish terrier',
  'schnauzer',
  'tibetan terrier',
  'west highland white terrier',
  'yorkshire terrier',
];
