module.exports = [
	'affenpinscher',
	'afghan hound',
	'afghan shepherd',
	'aidi',
	'airedale terrier',
	'akbash',
	'akita',
	'alano espanol',
	'alaskan husky',
	'alaskan klee kai',
	'alaskan malamute',
	'alaunt',
	'alopekis',
	'alpine dachsbracke',
	'alpine mastiff',
	'alpine spaniel',
	'american akita',
	'american bulldog',
	'american cocker spaniel',
	'american english coonhound',
	'american eskimo dog',
	'american foxhound',
	'american hairless terrier',
	'american pit bull terrier',
	'american staffordshire terrier',
	'american water spaniel',
	'anatolian shepherd dog',
	'andalusian hound',
	'anglo-francais de petite venerie',
	'appenzeller sennenhund',
	'ariege pointer',
	'ariegeois',
	'armant',
	'armenian gampr dog',
	'artois hound',
	'australian cattle dog',
	'australian kelpie',
	'australian shepherd',
	'australian silky terrier',
	'australian stumpy tail cattle dog',
	'australian terrier',
	'austrian black and tan hound',
	'austrian pinscher',
	'azawakh',
	'bakharwal dog',
	'barbet',
	'basenji',
	'basque ratter',
	'basque shepherd dog',
	'basset artesien normand',
	'basset bleu de gascogne',
	'basset fauve de bretagne',
	'grand basset griffon vendeen',
	'petit basset griffon vendeen',
	'basset hound',
	'bavarian mountain hound',
	'beagle',
	'beagle-harrier',
	'bearded collie',
	'beauceron',
	'bedlington terrier',
	'belgian groenendael',
	'belgian laekenois',
	'belgian malinois',
	'belgian tervuren',
	'bergamasco shepherd',
	'berger blanc suisse',
	'berger picard',
	'bernese mountain dog',
	'bichon frise',
	'billy',
	'black and tan coonhound',
	'black and tan virginia foxhound',
	'black norwegian elkhound',
	'black russian terrier',
	'black mouth cur',
	'grand bleu de gascogne',
	'petit bleu de gascogne',
	'bloodhound',
	'blue heeler',
	'blue lacy',
	'blue paul terrier',
	'blue picardy spaniel',
	'bluetick coonhound',
	'boerboel',
	'bohemian shepherd',
	'bolognese',
	'border collie',
	'border terrier',
	'borzoi',
	'bosnian coarse-haired hound',
	'boston terrier',
	'bouvier des ardennes',
	'bouvier des flandres',
	'boxer',
	'boykin spaniel',
	'bracco italiano',
	'braque d\'auvergne',
	'braque du bourbonnais',
	'braque du puy',
	'braque francais',
	'braque saint-germain',
	'brazilian dogo',
	'brazilian terrier',
	'briard',
	'briquet griffon vendeen',
	'brittany',
	'broholmer',
	'bruno jura hound',
	'bucovina shepherd dog',
	'bull and terrier',
	'bull terrier',
	'miniature bull terrier',
	'bulldog',
	'bullenbeisser',
	'bullmastiff',
	'bully kutta',
	'burgos pointer',
	'cairn terrier',
	'canaan dog',
	'canadian eskimo dog',
	'cane corso',
	'cantabrian water dog',
	'cao da serra de aires',
	'cao de castro laboreiro',
	'cao de gado transmontano',
	'cao fila de sao miguel',
	'carolina dog',
	'carpathian shepherd dog',
	'catahoula leopard dog',
	'catalan sheepdog',
	'caucasian shepherd dog',
	'cavalier king charles spaniel',
	'central asian shepherd dog',
	'cesky fousek',
	'cesky terrier',
	'chesapeake bay retriever',
	'chien francais blanc et noir',
	'chien francais blanc et orange',
	'chien francais tricolore',
	'chien-gris',
	'chihuahua',
	'chilean fox terrier',
	'chinese chongqing dog',
	'chinese crested dog',
	'chinese imperial dog',
	'chinook',
	'chippiparai',
	'chow chow',
	'cierny sery',
	'cirneco dell\'etna',
	'clumber spaniel',
	'rough collie',
	'smooth collie',
	'combai',
	'cordoba fighting dog',
	'coton de tulear',
	'cretan hound',
	'croatian sheepdog',
	'cumberland sheepdog',
	'curly-coated retriever',
	'cursinu',
	'czechoslovakian wolfdog',
	'dachshund',
	'dalmatian',
	'dandie dinmont terrier',
	'danish-swedish farmdog',
	'deutsche bracke',
	'doberman pinscher',
	'dogo argentino',
	'dogo cubano',
	'dogue de bordeaux',
	'drentse patrijshond',
	'drever',
	'dunker',
	'dutch shepherd',
	'dutch smoushond',
	'east siberian laika',
	'east european shepherd',
	'elo',
	'english cocker spaniel',
	'english foxhound',
	'english mastiff',
	'english setter',
	'english shepherd',
	'english springer spaniel',
	'black and tan english toy terrier',
	'english water spaniel',
	'english white terrier',
	'entlebucher mountain dog',
	'estonian hound',
	'estrela mountain dog',
	'eurasier',
	'eurohound',
	'field spaniel',
	'fila brasileiro',
	'finnish hound',
	'finnish lapphund',
	'finnish spitz',
	'flat-coated retriever',
	'smooth fox terrier',
	'wire fox terrier',
	'french brittany',
	'french bulldog',
	'french spaniel',
	'gaddi dog',
	'galgo espanol',
	'galician cattle dog',
	'garafian shepherd',
	'gascon saintongeois',
	'georgian shepherd dog',
	'german longhaired pointer',
	'german pinscher',
	'german roughhaired pointer',
	'german shepherd dog',
	'german shorthaired pointer',
	'german spaniel',
	'german spitz',
	'german wirehaired pointer',
	'giant schnauzer',
	'glen of imaal terrier',
	'golden retriever',
	'gordon setter',
	'gran mastin de borinquen',
	'grand anglo-francais blanc et noir',
	'grand anglo-francais blanc et orange',
	'grand anglo-francais tricolore',
	'grand griffon vendeen',
	'great dane',
	'great pyrenees',
	'greater swiss mountain dog',
	'greek harehound',
	'greenland dog',
	'greyhound',
	'griffon bleu de gascogne',
	'griffon bruxellois',
	'griffon fauve de bretagne',
	'griffon nivernais',
	'guatemalan dogo',
	'hamiltonstovare',
	'hanover hound',
	'hare indian dog',
	'harrier',
	'havanese',
	'hawaiian poi dog',
	'himalayan sheepdog',
	'hokkaido',
	'hortaya borzaya',
	'hovawart',
	'huntaway',
	'hygenhund',
	'ibizan hound',
	'icelandic sheepdog',
	'indian pariah dog',
	'indian spitz',
	'irish red and white setter',
	'irish setter',
	'irish terrier',
	'irish water spaniel',
	'irish wolfhound',
	'istrian coarse-haired hound',
	'istrian shorthaired hound',
	'italian greyhound',
	'jack russell terrier',
	'jagdterrier',
	'jamthund',
	'japanese chin',
	'japanese spitz',
	'japanese terrier',
	'kaikadi',
	'kai ken',
	'kangal dog',
	'kanni',
	'karakachan dog',
	'karelian bear dog',
	'karst shepherd',
	'keeshond',
	'kerry beagle',
	'kerry blue terrier',
	'king charles spaniel',
	'king shepherd',
	'kintamani',
	'kishu ken',
	'komondor',
	'kooikerhondje',
	'koolie',
	'korean jindo',
	'kromfohrlander',
	'kumaon mastiff',
	'kunming wolfdog',
	'kuri',
	'kuvasz',
	'kyi-leo',
	'labrador husky',
	'labrador retriever',
	'lagotto romagnolo',
	'lakeland terrier',
	'lancashire heeler',
	'landseer',
	'lapponian herder',
	'leonberger',
	'lhasa apso',
	'lithuanian hound',
	'lowchen',
	'mackenzie river husky',
	'magyar agar',
	'mahratta greyhound',
	'majorca ratter',
	'majorca shepherd dog',
	'maltese',
	'manchester terrier',
	'maremma sheepdog',
	'mcnab',
	'mexican hairless dog',
	'miniature australian shepherd',
	'miniature american shepherd',
	'miniature fox terrier',
	'miniature pinscher',
	'miniature schnauzer',
	'miniature shar pei',
	'mioritic',
	'molossus',
	'molossus of epirus',
	'montenegrin mountain hound',
	'moscow watchdog',
	'moscow water dog',
	'mountain cur',
	'mucuchies',
	'mudhol hound',
	'mudi',
	'large munsterlander',
	'small munsterlander',
	'neapolitan mastiff',
	'newfoundland',
	'new zealand heading dog',
	'norfolk spaniel',
	'norfolk terrier',
	'norrbottenspets',
	'north country beagle',
	'northern inuit dog',
	'norwegian buhund',
	'norwegian elkhound',
	'norwegian lundehund',
	'norwich terrier',
	'nova scotia duck tolling retriever',
	'old croatian sighthound',
	'old danish pointer',
	'old english sheepdog',
	'old english terrier',
	'old german shepherd dog',
	'old time farm shepherd',
	'olde english bulldogge',
	'otterhound',
	'pachon navarro',
	'pandikona hunting dog',
	'paisley terrier',
	'papillon',
	'parson russell terrier',
	'patterdale terrier',
	'pekingese',
	'perro de presa canario',
	'perro de presa mallorquin',
	'peruvian hairless dog',
	'phalene',
	'pharaoh hound',
	'phu quoc ridgeback',
	'picardy spaniel',
	'plummer terrier',
	'plott hound',
	'podenco canario',
	'pointer',
	'poitevin',
	'polish greyhound',
	'polish hound',
	'polish hunting dog',
	'polish lowland sheepdog',
	'polish tatra sheepdog',
	'pomeranian',
	'pont-audemer spaniel',
	'poodle',
	'porcelaine',
	'portuguese podengo',
	'portuguese pointer',
	'portuguese water dog',
	'posavac hound',
	'prazsky krysarik',
	'pudelpointer',
	'pug',
	'puli',
	'pumi',
	'pungsan dog',
	'pyrenean mastiff',
	'pyrenean shepherd',
	'rafeiro do alentejo',
	'rajapalayam',
	'rampur greyhound',
	'rastreador brasileiro',
	'ratonero bodeguero andaluz',
	'ratonero murciano de huerta',
	'ratonero valenciano',
	'rat terrier',
	'redbone coonhound',
	'rhodesian ridgeback',
	'rottweiler',
	'russian spaniel',
	'russian toy',
	'russian tracker',
	'russo-european laika',
	'russell terrier',
	'saarloos wolfdog',
	'sabueso espanol',
	'sabueso fino colombiano',
	'saint-usuge spaniel',
	'sakhalin husky',
	'saluki',
	'samoyed',
	'sapsali',
	'sarplaninac',
	'schapendoes',
	'schillerstovare',
	'schipperke',
	'standard schnauzer',
	'schweizer laufhund',
	'schweizerischer niederlaufhund',
	'scotch collie',
	'scottish deerhound',
	'scottish terrier',
	'sealyham terrier',
	'segugio italiano',
	'seppala siberian sleddog',
	'serbian hound',
	'serbian tricolour hound',
	'seskar seal dog',
	'shar pei',
	'shetland sheepdog',
	'shiba inu',
	'shih tzu',
	'shikoku',
	'shiloh shepherd',
	'siberian husky',
	'silken windhound',
	'sinhala hound',
	'skye terrier',
	'sloughi',
	'slovak cuvac',
	'slovakian rough-haired pointer',
	'slovensky kopov',
	'smalandsstovare',
	'small greek domestic dog',
	'soft-coated wheaten terrier',
	'south russian ovcharka',
	'southern hound',
	'spanish mastiff',
	'spanish water dog',
	'spinone italiano',
	'sporting lucas terrier',
	'st bernard',
	'st john\'s water dog',
	'stabyhoun',
	'staffordshire bull terrier',
	'stephens cur',
	'styrian coarse-haired hound',
	'sussex spaniel',
	'swedish lapphund',
	'swedish vallhund',
	'tahltan bear dog',
	'taigan',
	'taiwan dog',
	'talbot',
	'tamaskan dog',
	'teddy roosevelt terrier',
	'telomian',
	'tenterfield terrier',
	'terceira mastiff',
	'thai bangkaew dog',
	'thai ridgeback',
	'tibetan mastiff',
	'tibetan spaniel',
	'tibetan terrier',
	'tornjak',
	'tosa',
	'toy bulldog',
	'toy fox terrier',
	'toy manchester terrier',
	'toy trawler spaniel',
	'transylvanian hound',
	'treeing cur',
	'treeing tennessee brindle',
	'treeing walker coonhound',
	'trigg hound',
	'tweed water spaniel',
	'tyrolean hound',
	'uruguayan cimarron',
	'valencian ratter',
	'vanjari hound',
	'villano de las encartaciones',
	'vizsla',
	'volpino italiano',
	'weimaraner',
	'cardigan welsh corgi',
	'pembroke welsh corgi',
	'welsh sheepdog',
	'welsh springer spaniel',
	'welsh terrier',
	'west highland white terrier',
	'west siberian laika',
	'westphalian dachsbracke',
	'wetterhoun',
	'whippet',
	'white shepherd',
	'wirehaired pointing griffon',
	'wirehaired vizsla',
	'xiasi dog',
	'yorkshire terrier',
  'labradoodle',
  'goldendoodle',
  'cavoodle',
  'schnoodle',
  'chorkie',
  'chiweenie',
  'puggle',
  'groodle',
  'cavachon',
  'pekapoo',
];
