const wp = require('../index.js');

module.exports = {
  limit: 1,
  intro: 20,
  sections: 1,
  count: 5,
  category: '22',
  privacy: 'public',
  template: 'list',
  keywordType: 'PLURAL',
  keywordPlural: true,
  keywordDeterminer: 'a',
  keywordNoun: 'product',
  keywordList: ['slow dog bowls','slow dog feeders'],
  link: '',
  amazon: true,
  cacheOnly: true,
  multipleOnly: true,
  slideshows: 1,
  assets: '/Users/brentmccoy/Apps/node-modules/bmjs-webparser/assets/',
  images: '/Users/brentmccoy/Apps/node-modules/bmjs-webparser/cache/images/',
  voice: 'karen',
  shuffle: false,
  random: true,
  matchRegex: null,
  strict: true,
  minLength: 0,
  imageKeywords: []
};
